--------------------------------------------------------
--  File created - Sreda-marec-28-2018   
--------------------------------------------------------
REM INSERTING into DRZAVE
SET DEFINE OFF;
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('1','Slovenija');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('2','Nemcija');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('3','Avstrija');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('4','Kitajska');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('5','Japonska');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('6','Amerika');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('7','Kanada');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('8','Avstralija');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('9','Italija');
Insert into SSK1_DRZAVE (ID_DRZAVE,DRZAVA) values ('10','Francija');

REM INSERTING into TEKMOVALCI
SET DEFINE OFF;
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('1','Billy','Pedigo','1');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('2','Richard','Aaron','3');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('3','Mildred','Blue','10');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('4','Richard','Bolin','2');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('5','Jose','McConnell','9');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('6','Susan','Perry','4');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('7','Josephine','Gonzalez','6');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('8','Garry','Chrisman','6');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('9','Pamela','Leon','4');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('10','Minnie','Frick','10');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('11','Bobby','Smith','1');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('12','Shannon','Phillips','4');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('13','Elizabeth','Grand','7');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('14','Erica','Gaither','8');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('15','Carmen','Matthews','9');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('16','Ellen','Robinson','4');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('17','Karlton','Spencer','6');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('18','Donald','Trump','6');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('19','Eric','Iser','8');
Insert into SSK1_TEKMOVALCI (ID_TEKMOVALCA,IME,PRIIMEK,ID_DRZAVE) values ('20','Richard','Waters','5');

REM INSERTING into SKAKALNICE
SET DEFINE OFF;
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('1','Copper Peak');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('2','Kulm');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('3','Letalnica bratov Gori�ek');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('4','Letalnica Heini Klopfer');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('5','Letalnica �ertak');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('6','Planica');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('7','Vikersundbakken');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('8','Vikkollen');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('9','Nels Nelsen Hill');
Insert into SSK1_SKAKALNICE (ID_SKAKALNICE,IME_SKAKALNICE) values ('10','Trampolino Gigante Corno d�Aola');

REM INSERTING into TEKMOVANJA
SET DEFINE OFF;
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('1','Pokal narodov',to_date('01.10.05','DD.MM.RR'),'6');
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('2','Dr�avno',to_date('11.01.01','DD.MM.RR'),'3');
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('3','Evropsko',to_date('14.06.02','DD.MM.RR'),'9');
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('4','Svetovno',to_date('22.08.17','DD.MM.RR'),'8');
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('5','Milky Way',to_date('15.10.10','DD.MM.RR'),'8');
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('6','Univerzalno',to_date('10.09.03','DD.MM.RR'),'9');
Insert into SSK1_TEKMOVANJA (ID_TEKMOVANJA,NAZIV,DATUM,ID_SKAKALNICE) values ('7','Vesoljno',to_date('05.12.13','DD.MM.RR'),'10');

REM INSERTING into SKOK_STATUSI
SET DEFINE OFF;
Insert into SSK1_SKOK_STATUSI (ID_STATUSA,STATUS) values ('1','Opravljen');
Insert into SSK1_SKOK_STATUSI (ID_STATUSA,STATUS) values ('2','Neopravljen');
Insert into SSK1_SKOK_STATUSI (ID_STATUSA,STATUS) values ('3','Razveljavljen');

REM INSERTING into SKOKI
SET DEFINE OFF;
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('1','1','6','1.','166,7','9,3','1','D',to_date('01.10.05','DD.MM.RR'),to_date('21.09.05','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('2','3','1','1.','154,1','8,6','2','D',to_date('14.06.02','DD.MM.RR'),to_date('04.06.02','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('3','2','2','1.','174,7','6,6','1','D',to_date('11.01.01','DD.MM.RR'),to_date('05.01.01','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('4','1','3','1.','179,7','5,5','2','D',to_date('01.10.05','DD.MM.RR'),to_date('25.09.05','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('5','2','4','1.','158,9','18,3','2','D',to_date('11.01.01','DD.MM.RR'),to_date('07.01.01','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('6','4','5','1.','194,3','19,8','1','D',to_date('22.08.17','DD.MM.RR'),to_date('14.08.17','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('7','4','6','1.','156,4','5,5','2','D',to_date('22.08.17','DD.MM.RR'),to_date('14.08.17','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('8','2','7','1.','191,2','6,3','1','D',to_date('11.01.01','DD.MM.RR'),to_date('01.01.01','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('9','2','8','1.','173,8','1,4','2','D',to_date('11.01.01','DD.MM.RR'),to_date('07.01.01','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('10','4','9','1.','181,1','13,4','2','D',to_date('22.08.17','DD.MM.RR'),to_date('12.08.17','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('11','1','10','1.','155,8','19,3','2','D',to_date('01.10.05','DD.MM.RR'),to_date('21.09.05','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('12','7','11','1.','170,1','13,4','3','D',to_date('05.12.13','DD.MM.RR'),to_date('04.12.13','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('13','5','12','1.','179,5','11,1','3','D',to_date('15.10.10','DD.MM.RR'),to_date('10.10.10','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('14','6','13','1.','180,9','3,3','2','D',to_date('10.09.03','DD.MM.RR'),to_date('07.09.03','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('15','7','14','1.','186,7','14,6','3','D',to_date('05.12.13','DD.MM.RR'),to_date('30.11.13','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('16','3','15','1.','184,2','11,1','2','D',to_date('14.06.02','DD.MM.RR'),to_date('10.06.02','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('17','3','16','1.','194,5','3','1','D',to_date('14.06.02','DD.MM.RR'),to_date('12.06.02','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('18','7','17','1.','154,8','13,2','3','D',to_date('05.12.13','DD.MM.RR'),to_date('30.11.13','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('19','4','18','1.','174,8','17,5','2','D',to_date('22.08.17','DD.MM.RR'),to_date('19.08.17','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('20','1','19','1.','162,7','13,2','2','D',to_date('01.10.05','DD.MM.RR'),to_date('25.09.05','DD.MM.RR'));
Insert into SSK1_SKOKI (ID_SKOKA,ID_TEKMOVANJA,ID_TEKMOVALCA,SERIJA,DOLZINA_SKOKA,OCENA_SKOKA,ID_STATUSA,PRIJAVE_ZAKLJUCENE,STARTNI_CAS,DATUM_PRIJAVE) values ('21','6','20','1.','177','8,3','1','D',to_date('10.09.03','DD.MM.RR'),to_date('07.09.03','DD.MM.RR'));

COMMIT;